name       : ddgr
version    : 1.7
release    : 4
source     :
    - https://github.com/jarun/ddgr/archive/v1.7.tar.gz : 1e3d01dc71337b2a59b96ab89ee422a7ef9e6ddcd42813ac08d57db194bc4fea
license    : GPL-3.0-or-later
component  : network.clients
summary    : DuckDuckGo from the terminal
description: |
    ddgr is a cmdline utility to search DuckDuckGo from the terminal.
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 ddgr.1 $installdir/usr/share/man/man1/ddgr.1
    install -Dm00644 auto-completion/bash/ddgr-completion.bash $installdir/usr/share/bash-completion/completions/ddgr
    install -Dm00644 auto-completion/fish/ddgr.fish $installdir/usr/share/fish/vendor_completions.d/ddgr.fish
    install -Dm00644 auto-completion/zsh/_ddgr $installdir/usr/share/zsh/site-functions/_ddgr
