name       : ddgr
version    : 1.9
release    : 6 
source     :
    - https://github.com/jarun/ddgr/archive/v1.9.tar.gz : 3dfe82fab649f1cec904a1de63f78692be329a3b6928c1615f22c76f6e21c36f
license    : GPL-3.0-or-later
component  : network.clients
summary    : DuckDuckGo from the terminal
description: |
    ddgr is a cmdline utility to search DuckDuckGo from the terminal.
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 ddgr.1 $installdir/usr/share/man/man1/ddgr.1
    install -Dm00644 auto-completion/bash/ddgr-completion.bash $installdir/usr/share/bash-completion/completions/ddgr
    install -Dm00644 auto-completion/fish/ddgr.fish $installdir/usr/share/fish/vendor_completions.d/ddgr.fish
    install -Dm00644 auto-completion/zsh/_ddgr $installdir/usr/share/zsh/site-functions/_ddgr
