name       : ddgr
version    : '2.1'
release    : 10
source     :
    - https://github.com/jarun/ddgr/archive/refs/tags/v2.1.tar.gz : fb6601ad533f2925d2d6299ab9e6dd48da0b75e99ef9ed9068f37e516380b5e6
license    : GPL-3.0-or-later
homepage   : https://github.com/jarun/ddgr
component  : network.clients
summary    : DuckDuckGo from the terminal
description: |
    ddgr is a cmdline utility to search DuckDuckGo from the terminal.
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 ddgr.1 $installdir/usr/share/man/man1/ddgr.1
    install -Dm00644 auto-completion/bash/ddgr-completion.bash $installdir/usr/share/bash-completion/completions/ddgr
    install -Dm00644 auto-completion/fish/ddgr.fish $installdir/usr/share/fish/vendor_completions.d/ddgr.fish
    install -Dm00644 auto-completion/zsh/_ddgr $installdir/usr/share/zsh/site-functions/_ddgr
