name       : ddgr
version    : 1.4
release    : 1
source     :
    - https://github.com/jarun/ddgr/archive/v1.4.tar.gz : 045063b4d7262992a7ea3cd9fe9715a199318828de82073f54c42631d3ef41b7
license    : GPL-3.0-or-later
component  : network.clients
summary    : DuckDuckGo from the terminal 
description: |
    ddgr is a cmdline utility to search DuckDuckGo from the terminal.
rundeps    :
    - python3
install    : |
    PREFIX=/usr %make_install

    install -Dm00644 $workdir/auto-completion/bash/ddgr-completion.bash $installdir/usr/share/bash-completion/completions/ddgr
    install -Dm00644 $workdir/auto-completion/fish/ddgr.fish $installdir/usr/share/fish/vendor_completions.d/ddgr.fish
    install -Dm00644 $workdir/auto-completion/zsh/_ddgr $installdir/usr/share/zsh/site-functions/_ddgr
